JD-444 exclude notofifacations api
rbkmoney/dudoser pull request #105
Opened 2021-08-17 15:44 UTC by ElenaKushchenko

2021-08-17 20:50 UTC, PospolitaNV reviewed
![image](https://user-images.githubusercontent.com/9200956/129798701-96897d94-7edd-4d7d-b808-4fd06b1e1fa8.png)
:D

2021-08-18 09:26 UTC, PospolitaNV requested changes

2021-08-18 09:26 UTC, PospolitaNV commented on src/main/java/com/rbkmoney/dudoser/converter/MailingExclusionRuleConverter.java
> +    public void convert(MessageExclusionRule from, MailingExclusionRule to) {
Давай сделаем нейминг fromThrift и toThrift, очень плохо читаются два метода (на ревью по крайней мере)

2021-08-18 09:26 UTC, PospolitaNV commented on src/main/java/com/rbkmoney/dudoser/dao/MailingExclusionRuleType.java
> +    }
Где-то грустит один Ломбок

2021-08-18 09:26 UTC, PospolitaNV commented on src/main/java/com/rbkmoney/dudoser/handler/poller/InvoicePaymentStatusChangedHandler.java
> +            log.info("Mailing has been disabled for shopId={}", shopId);
давай ещё список правил кинем (ids)

2021-08-18 09:37 UTC, ggmaleva commented on src/main/java/com/rbkmoney/dudoser/dao/MailingExclusionRuleDao.java
> +    Long createExclusionRule(MailingExclusionRule messageExclusionRule);
У тебя в название сервиса есть сущность, о которой речь. 
Думаю, можно выпилить ее из названий методов :)

2021-08-18 09:39 UTC, ElenaKushchenko commented on src/main/java/com/rbkmoney/dudoser/dao/MailingExclusionRuleDao.java
> +    Long createExclusionRule(MailingExclusionRule messageExclusionRule);
Ну ок)

2021-08-18 11:26 UTC, PospolitaNV submitted a review, later dismissed

2021-08-30 08:27 UTC, merged